CardComWebApplication/Models/AddPersonViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace CardComWebApplication.Models
{
    public class AddPersonViewModel
    {
        [Required(ErrorMessage = "ID is required")]
        [RegularExpression(@"^[0-9]{9,9}$", ErrorMessage = "Must be 9 digits long. only numbers ")]
        public string ID { get; set; }


        [Required(ErrorMessage = "Name is required")]
        public string Name { get; set; }

        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Birthdate is required")]
        [DataType(DataType.Date)]
        public DateTime Birthdate { get; set; }

        public Gender? Gender { get; set; }


        [RegularExpression("^[0-9]{9,10}$", ErrorMessage = "Phone must contain 9 or 10 digits, only digits")]
        public string Phone { get; set; }

    }

    public enum Gender
    {
        Male,
        Female,
        Other
    }
}

CardComWebApplication/Models/Domain/Person.cs
namespace CardComWebApplication.Models.Domain
{
    public class Person
    {
    
        public string ID { get; set; }

        public string Name { get; set; }

        public string Email { get; set; }

        public DateTime Birthdate { get; set; }
    
        public string Gender { get; set; }

        public string Phone { get; set; }

        
    }


}

CardComWebApplication/Models/EditPersonViewModel.cs
using CardComWebApplication.Models.Domain;
using System.ComponentModel.DataAnnotations;

namespace CardComWebApplication.Models
{
    public class EditPersonViewModel
    {

            [Required(ErrorMessage = "ID is required")]
            [RegularExpression(@"^[0-9]{9,9}$", ErrorMessage = "Must be 9 digits long. only numbers ")]
            public string ID { get; set; }


            [Required(ErrorMessage = "Name is required")]
            public string Name { get; set; }

            [EmailAddress(ErrorMessage = "Invalid Email Address")]
            public string Email { get; set; }

            [Required(ErrorMessage = "Birthdate is required")]
            [DataType(DataType.Date)]
            public DateTime Birthdate { get; set; }

            public Gender? Gender { get; set; }


            [RegularExpression("^[0-9]{9,10}$", ErrorMessage = "Phone must contain 9 or 10 digits, only digits")]
            public string Phone { get; set; }


    }

        
}

CardComWebApplication/Models/ErrorViewModel.cs
namespace CardComWebApplication.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CardComWebApplication/Controllers/HomeController.cs
using CardComWebApplication.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CardComWebApplication.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CardComWebApplication/Controllers/PersonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CardComWebApplication.Data;
using CardComWebApplication.Models.Domain;
using System.Net;
using CardComWebApplication.Models;
using CardComWebApplication.Services;
using System.Data;

namespace CardComWebApplication.Controllers
{
    public class PersonController : Controller
    {
        private readonly IPersonService _personService;
        public PersonController(IPersonService personService)
        {
            _personService = personService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var person =  _personService.GetPersons();
            return View(person);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        
        [HttpPost]
        public IActionResult Add(AddPersonViewModel addPersonRequest)
        {
            if (ModelState.IsValid)
            {
                // Check for uniqueness
                if (!_personService.IsEmailUnique(addPersonRequest.Email))
                {
                    ModelState.AddModelError("Email", "Email address already exists.");
                    return View(addPersonRequest);
                }

                if (!_personService.IsIdUnique(addPersonRequest.ID))
                {
                    ModelState.AddModelError("ID", "ID already exists.");
                    return View(addPersonRequest);
                }

                if (!_personService.IsPhoneUnique(addPersonRequest.Phone))
                {
                    ModelState.AddModelError("Phone", "Phone number already exists.");
                    return View(addPersonRequest);
                }

                // If everything is okay, proceed to save to the database
                _personService.AddPerson(addPersonRequest);

                return RedirectToAction("Index");
            }

            // If the model state is not valid, return the view with errors
            return View(addPersonRequest);
        }

        [HttpGet]
        public IActionResult Edit(string id)
        {
            var person = _personService.GetPersonById(id);

            // If the person is not found, return NotFound
            if (person == null)
            {
                return NotFound();
            }

            EditPersonViewModel editViewModel = MapToEditViewModel(person);

            return View(editViewModel);
        }

        private EditPersonViewModel MapToEditViewModel(Person person)
        {
            return new EditPersonViewModel
            {
                ID = person.ID,
                Name = person.Name,
                Email = person.Email,
                Birthdate = person.Birthdate,
                Phone = person.Phone
            };
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(EditPersonViewModel editpersonViewModel)
        {
            // Fetch the existing person from the database
            var existingPerson = _personService.GetPersonById(editpersonViewModel.ID);

            // Check uniqueness, excluding the current person's ID
            if (_personService.IsIDUniqueEdit(editpersonViewModel.ID, existingPerson.ID) &&
                _personService.IsEmailUniqueEdit(editpersonViewModel.ID, existingPerson.ID) &&
                _personService.IsPhoneUniqueEdit(editpersonViewModel.ID, existingPerson.ID)
                )
            {
                // Your update logic
                _personService.EditPerson(existingPerson,editpersonViewModel);
                return RedirectToAction("Index");
            }
            else
            {
                // Set a validation error
                ModelState.AddModelError("ID","The ID,Email,Phone must be unique.");
                return View(editpersonViewModel);
            }
        }



		[HttpGet]
		public IActionResult Delete(string id)
		{
            var person = _personService.GetPersonById(id);

            // If the person is not found, return NotFound
            if (person == null)
            {
                return NotFound();
            }

            return View(person);
        }

		[HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(Person person)
        {
            _personService.DeletePerson(person.ID);

            return RedirectToAction("Index");
        }
    }


}

CardComWebApplication/Views/Home/Index.cshtml
@model List<CardComWebApplication.Models.Domain.Person>


@{
}
<h1>Person List</h1>
<li class="nav-item">
	<a class="nav-link text-dark" asp-area="" asp-controller="Person" asp-action="Add">Add Person</a>
</li>
<table class="table">
	<thead>
		<tr>
			<th>ID</th>
			<th>Name</th>
			<th>E-mail</th>
			<th>Date of Birth</th>
			<th>Gender</th>
			<th>Phone</th>
		</tr>
	</thead>
	<tbody>
		@if(Model!=null)
		{
			@foreach (var person in Model)
			{
			<tr>
				<td>@person.ID</td>
				<td>@person.Name</td>
				<td>@person.Email</td>
				<td>@person.Birthdate</td>
				<td>@person.Gender</td>
				<td>@person.Phone</td>s
				<td><a href="Person/Edit/@person.ID">Edit Person</a></td>
				<td><a href="Person/Delete/@person.ID">Delete person</a></td>
				
			</tr>
			}
		}
		else
		{
			<p>No Person available</p>
			Console.WriteLine("problem");
			;		}
	</tbody>
</table>

CardComWebApplication/Views/Person/Add.cshtml
@using CardComWebApplication.Models
@model CardComWebApplication.Models.AddPersonViewModel

@{
    ViewBag.Title = "Add Person";
}

<h2>Add Person</h2>

@using (Html.BeginForm("Add", "Person", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(model => model.ID)
        @Html.TextBoxFor(model => model.ID, new { @class = "form-control", type = "number" })
        @Html.ValidationMessageFor(model => model.ID)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Name)
        @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Name)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email)
        @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Email)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Birthdate)
        @Html.EditorFor(model => model.Birthdate, new { @class = "form-control", type = "date" })
        @Html.ValidationMessageFor(model => model.Birthdate)
    </div>
    
    <div class="form-group">
        <label asp-for="Gender" class="control-label"></label>
        <select asp-for="Gender" class="form-control">
            @foreach (var value in Enum.GetValues(typeof(Gender)))
            {
                <option value="@value">@value</option>
            }
        </select>
        <span asp-validation-for="Gender" class="text-danger"></span>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Phone)
        @Html.TextBoxFor(model => model.Phone, new { @class = "form-control", type = "tel" })
        @Html.ValidationMessageFor(model => model.Phone)
    </div>

    <div class="form-group">
        <input type="submit" value="Add" class="btn btn-primary" />
    </div>
}

CardComWebApplication/Views/Person/Create.cshtml
@model CardComWebApplication.Models.Domain.Person

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Person</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ID" class="control-label"></label>
                <input asp-for="ID" class="form-control" />
                <span asp-validation-for="ID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Birthdate" class="control-label"></label>
                <input asp-for="Birthdate" class="form-control" />
                <span asp-validation-for="Birthdate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <input asp-for="Gender" class="form-control" />
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

CardComWebApplication/Views/Person/Delete.cshtml
@model CardComWebApplication.Models.Domain.Person

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Person</h4>
    <hr />
    <div>
        <p>ID: @Model.ID</p>
        <p>Name: @Model.Name</p>
        <p>Email: @Model.Email</p>
        <p>Birth Date: @Model.Birthdate</p>
        <p>Gender: @Model.Gender</p>
        <p>Phone: @Model.Phone</p>
    </div>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CardComWebApplication/Views/Person/Details.cshtml
@model CardComWebApplication.Models.Domain.Person

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Person</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Birthdate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Birthdate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CardComWebApplication/Views/Person/Edit.cshtml
@model EditPersonViewModel

<h2>Edit Person</h2>

<form asp-action="Edit">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="ID" class="control-label"></label>
        <input asp-for="ID" class="form-control"/>
        <span asp-validation-for="ID" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Name" class="control-label"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Email" class="control-label"></label>
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>

     <div class="form-group">
        <label asp-for="Birthdate" class="control-label"></label>
        <input asp-for="Birthdate" type="date" class="form-control" />
        <span asp-validation-for="Birthdate" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Gender" class="control-label"></label>
        <select asp-for="Gender" class="form-control">
            @foreach (var value in Enum.GetValues(typeof(Gender)))
            {
                <option value="@value">@value</option>
            }
        </select>
        <span asp-validation-for="Gender" class="text-danger"></span>
    </div>

     <div class="form-group">
        <label asp-for="Phone" class="control-label"></label>
        <input asp-for="Phone" class="form-control" />
        <span asp-validation-for="Phone" class="text-danger"></span>
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-primary">Save Changes</button>
    </div>
</form>

CardComWebApplication/Views/Person/Index.cshtml
@model List<CardComWebApplication.Models.Domain.Person>


@{
}
<h1>Person List</h1>
<li class="nav-item">
	<a class="nav-link text-dark" asp-area="" asp-controller="Person" asp-action="Add">Add Person</a>
</li>
<table class="table">
	<thead>
		<tr>
			<th>ID</th>
			<th>Name</th>
			<th>E-mail</th>
			<th>Date of Birth</th>
			<th>Gender</th>
			<th>Phone</th>
		</tr>
	</thead>
	<tbody>
		@if (Model != null)
		{
			@foreach (var person in Model)
			{
				<tr>
					<td>@person.ID</td>
					<td>@person.Name</td>
					<td>@person.Email</td>
					<td>@person.Birthdate</td>
					<td>@person.Gender</td>
					<td>@person.Phone</td>s
					<td><a href="Person/Edit/@person.ID">Edit Person</a></td>
					<td><a href="Person/Delete/@person.ID">Delete person</a></td>

				</tr>
			}
		}
		else
		{
			<p>No Person available</p>
		}
	</tbody>
</table>

CardComWebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CardComWebApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CardComWebApplication.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Person" asp-action="Index">CardComWebApplication</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Person" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CardComWebApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>